import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json([
    {
      id: 1,
      name: "Taj Mahal",
      country: "India",
      state: "Uttar Pradesh",
      risk: "Low",
      score: 20,
      reason: "Well maintained and protected",
      lat: 27.1751,
      lng: 78.0421,
      famous: true,
      description: "An immense mausoleum of white marble, built in Agra between 1631 and 1648 by order of the Mughal emperor Shah Jahan."
    },
    {
      id: 2,
      name: "Sundarbans National Park",
      country: "India",
      state: "West Bengal",
      risk: "Medium",
      score: 55,
      reason: "Climate change and rising sea levels",
      lat: 21.9497,
      lng: 89.1833,
      famous: false,
      description: "The Sundarbans mangrove forest, one of the largest such forests in the world, lies on the delta of the Ganges, Brahmaputra and Meghna rivers on the Bay of Bengal."
    },
    {
      id: 3,
      name: "Hampi Ruins",
      country: "India",
      state: "Karnataka",
      risk: "Medium",
      score: 42,
      reason: "Tourism footfall and weathering of old structures",
      lat: 15.3350,
      lng: 76.4600,
      famous: true,
      description: "The austere, grandiose site of Hampi was the last capital of the Hindu Kingdom of Vijayanagara."
    },
    {
      id: 4,
      name: "Colosseum",
      country: "Italy",
      state: "Lazio",
      risk: "Low",
      score: 25,
      reason: "Strong preservation efforts",
      lat: 41.8902,
      lng: 12.4922,
      famous: true,
      description: "An elliptical amphitheatre in the centre of the city of Rome, Italy, the largest ancient amphitheatre ever built."
    },
    {
      id: 5,
      name: "Machu Picchu",
      country: "Peru",
      state: "Cuzco",
      risk: "Medium",
      score: 58,
      reason: "Tourism pressure",
      lat: -13.1631,
      lng: -72.5450,
      famous: true,
      description: "An Incan citadel set high in the Andes Mountains in Peru, built in the 15th century and later abandoned."
    },
    {
      id: 6,
      name: "Ajanta Caves",
      country: "India",
      state: "Maharashtra",
      risk: "High",
      score: 75,
      reason: "Moisture degradation affecting ancient murals",
      lat: 20.5519,
      lng: 75.7031,
      famous: true,
      description: "The first Buddhist cave monuments of Ajanta date from the 2nd and 1st centuries B.C."
    },
    {
      id: 7,
      name: "Sun Temple, Konark",
      country: "India",
      state: "Odisha",
      risk: "High",
      score: 80,
      reason: "Saline air corrosion and structural strain",
      lat: 19.8876,
      lng: 85.8245,
      famous: true,
      description: "On the shores of the Bay of Bengal, the temple at Konark is a monumental representation of the sun god Surya's chariot."
    },
    {
      id: 8,
      name: "Brihadisvara Temple",
      country: "India",
      state: "Tamil Nadu",
      risk: "Low",
      score: 18,
      reason: "Excellent preservation, urban environmental monitoring",
      lat: 10.7828,
      lng: 79.1318,
      famous: true,
      description: "One of the greatest architectural achievements of the Chola Dynasty, built entirely in granite."
    },
    {
      id: 9,
      name: "Qutub Minar Complex",
      country: "India",
      state: "Delhi",
      risk: "Low",
      score: 22,
      reason: "Strict ASI conservation, air pollution monitoring",
      lat: 28.5245,
      lng: 77.1855,
      famous: true,
      description: "Red sandstone tower built in the early 13th century, standing at 72.5 meters tall."
    },
    {
      id: 10,
      name: "Khajuraho Temples",
      country: "India",
      state: "Madhya Pradesh",
      risk: "Medium",
      score: 45,
      reason: "Weathering and sandstone erosion",
      lat: 24.8518,
      lng: 79.9218,
      famous: true,
      description: "Temples belonging to the Hindu and Jain religions, famous for their architectural majesty and sculpture art."
    },
    {
      id: 11,
      name: "Hawa Mahal",
      country: "India",
      state: "Rajasthan",
      risk: "Low",
      score: 30,
      reason: "Active state tourism maintenance and heritage corridor restoration",
      lat: 26.9239,
      lng: 75.8267,
      famous: true,
      description: "Built in 1799, the Palace of Winds is shaped like a crown of Krishna, with 953 small windows (jharokhas)."
    },
    {
      id: 12,
      name: "Mohenjo-daro",
      country: "Pakistan",
      state: "Sindh",
      risk: "High",
      score: 85,
      reason: "Weather erosion and degradation",
      lat: 27.3294,
      lng: 68.1386,
      famous: false,
      description: "The ruins of the huge city of Mohenjo-daro - built entirely of unbaked brick in the 3rd millennium B.C. - lie in the Indus Valley."
    }
  ]);
}